/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeKnowRouteImport } from './routes/we-know'
import { Route as LoSappiamoRouteImport } from './routes/lo-sappiamo'
import { Route as EnRouteImport } from './routes/en'
import { Route as IndexRouteImport } from './routes/index'

const WeKnowRoute = WeKnowRouteImport.update({
  id: '/we-know',
  path: '/we-know',
  getParentRoute: () => rootRouteImport,
} as any)
const LoSappiamoRoute = LoSappiamoRouteImport.update({
  id: '/lo-sappiamo',
  path: '/lo-sappiamo',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/lo-sappiamo': typeof LoSappiamoRoute
  '/we-know': typeof WeKnowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/lo-sappiamo': typeof LoSappiamoRoute
  '/we-know': typeof WeKnowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/lo-sappiamo': typeof LoSappiamoRoute
  '/we-know': typeof WeKnowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/en' | '/lo-sappiamo' | '/we-know'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/en' | '/lo-sappiamo' | '/we-know'
  id: '__root__' | '/' | '/en' | '/lo-sappiamo' | '/we-know'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRoute
  LoSappiamoRoute: typeof LoSappiamoRoute
  WeKnowRoute: typeof WeKnowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/we-know': {
      id: '/we-know'
      path: '/we-know'
      fullPath: '/we-know'
      preLoaderRoute: typeof WeKnowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lo-sappiamo': {
      id: '/lo-sappiamo'
      path: '/lo-sappiamo'
      fullPath: '/lo-sappiamo'
      preLoaderRoute: typeof LoSappiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRoute,
  LoSappiamoRoute: LoSappiamoRoute,
  WeKnowRoute: WeKnowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
